/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ["class"],
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        "inverse-primary": "#c3c0ff",
        "tertiary-fixed": "#6ffbbe",
        "surface-bright": "#fcf8ff",
        "surface-container": "#f0ecf4",
        "surface-container-low": "#f6f2fa",
        "on-tertiary-fixed-variant": "#005236",
        "on-error": "#ffffff",
        "surface": "#fcf8ff",
        "on-secondary-container": "#57657a",
        "inverse-surface": "#303036",
        "on-tertiary-container": "#14ba82",
        "on-primary-fixed": "#100563",
        "surface-container-highest": "#e5e1e9",
        "error-container": "#ffdad6",
        "error": "#ba1a1a",
        "surface-container-high": "#eae7ef",
        "on-primary": "#ffffff",
        "surface-tint": "#5654a8",
        "secondary-fixed-dim": "#b9c7df",
        "on-tertiary": "#ffffff",
        "on-primary-fixed-variant": "#3e3c8f",
        "primary-fixed-dim": "#c3c0ff",
        "on-background": "#1b1b21",
        "on-secondary-fixed-variant": "#3a485b",
        "secondary-fixed": "#d5e3fc",
        "surface-container-lowest": "#ffffff",
        "tertiary-container": "#00432c",
        "primary-fixed": "#e2dfff",
        "on-secondary": "#ffffff",
        "primary": "#1a146b",
        "inverse-on-surface": "#f3eff7",
        "on-error-container": "#93000a",
        "tertiary-fixed-dim": "#4edea3",
        "outline-variant": "#c8c5d3",
        "on-surface-variant": "#474651",
        "surface-dim": "#dcd9e0",
        "background": "#fcf8ff",
        "outline": "#777682",
        "on-secondary-fixed": "#0d1c2e",
        "secondary": "#515f74",
        "on-surface": "#1b1b21",
        "tertiary": "#002b1b",
        "secondary-container": "#d5e3fc",
        "surface-variant": "#e5e1e9",
        "on-tertiary-fixed": "#002113",
        "on-primary-container": "#9c9af4",
        "primary-container": "#312e81",
        border: "#c8c5d3",
        input: "#f0ecf4",
        ring: "#1a146b"
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [],
}
